# Pandas file read write operation from web api

# web APIS

In [4]:
import requests
url="https://api.github.com/repos/pandas-dev/pandas/issues"
resp=requests.get(url)

In [5]:
type(resp)

requests.models.Response

In [6]:
resp

In [12]:
data=resp.json()
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40629',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40629/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40629/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40629/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/40629',
  'id': 840609480,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NjAwNDcxMTM1',
  'number': 40629,
  'title': 'Detect Parsing errors in read_csv first row with index_col=False',
  'user': {'login': 'njriasan',
   'id': 28767570,
   'node_id': 'MDQ6VXNlcjI4NzY3NTcw',
   'avatar_url': 'https://avatars.githubusercontent.com/u/28767570?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/njriasan',
   'html_url': 'https://github.com/njriasan',
   'followers_url': 'https://api.github.com/users/njriasan/followers',
   'following_url': 'https://api.github.com/users/njriasan/following{/other_user}',
   'gists_url': 'https://api.github.com/users/njriasan/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/njriasan/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/njriasan/subscriptions',
   'organizations_url': 'https://api.github.com/users/njriasan/orgs',
   'repos_url': 'https://api.github.com/users/njriasan/repos',
   'events_url': 'https://api.github.com/users/njriasan/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/njriasan/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2021-03-25T06:32:30Z',
  'updated_at': '2021-03-25T07:10:04Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/40629',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/40629',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/40629.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/40629.patch'},
  'body': '\r\n- [X] closes #40333\r\n- [ ] tests added / passed\r\n- [X] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\r\n- [X] whatsnew entry\r\n',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40628',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40628/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40628/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40628/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/40628',
  'id': 840584176,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NjAwNDQ5NjU0',
  'number': 40628,
  'title': 'New boundary inputs',
  'user': {'login': 'hewittk',
   'id': 42876297,
   'node_id': 'MDQ6VXNlcjQyODc2Mjk3',
   'avatar_url': 'https://avatars.githubusercontent.com/u/42876297?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/hewittk',
   'html_url': 'https://github.com/hewittk',
   'followers_url': 'https://api.github.com/users/hewittk/followers',
   'following_url': 'https://api.github.com/users/hewittk/following{/other_user}',
   'gists_url': 'https://api.github.com/users/hewittk/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/hewittk/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/hewittk/subscriptions',
   'organizations_url': 'https://api.github.com/users/hewittk/orgs',
   'repos_url': 'https://api.github.com/users/hewittk/repos',
   'events_url': 'https://api.github.com/users/hewittk/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/hewittk/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2021-03-25T05:52:36Z',
  'updated_at': '2021-03-25T06:29:50Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/40628',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/40628',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/40628.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/40628.patch'},
  'body': '- [x] closes #40245\r\n- [x] tests added / passed\r\n- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\r\n- [x] whatsnew entry\r\n',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40626',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40626/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40626/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40626/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/40626',
  'id': 840554057,
  'node_id': 'MDU6SXNzdWU4NDA1NTQwNTc=',
  'number': 40626,
  'title': 'BUG: I got empty Dataframe with index from the summation of empty Dataframe with MultiIndex',
  'user': {'login': 'llthelinkll',
   'id': 5256282,
   'node_id': 'MDQ6VXNlcjUyNTYyODI=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/5256282?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/llthelinkll',
   'html_url': 'https://github.com/llthelinkll',
   'followers_url': 'https://api.github.com/users/llthelinkll/followers',
   'following_url': 'https://api.github.com/users/llthelinkll/following{/other_user}',
   'gists_url': 'https://api.github.com/users/llthelinkll/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/llthelinkll/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/llthelinkll/subscriptions',
   'organizations_url': 'https://api.github.com/users/llthelinkll/orgs',
   'repos_url': 'https://api.github.com/users/llthelinkll/repos',
   'events_url': 'https://api.github.com/users/llthelinkll/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/llthelinkll/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2021-03-25T04:49:03Z',
  'updated_at': '2021-03-25T06:26:43Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': "I'm not sure that the current behavior is right, so I would like to ask. \r\n\r\nWhen I have a non-empty Dataframe I can use `sum(level=['Project', 'Task''])` to get the MultiIndex Dataframe as my expectation. But when I try to sum the empty Dataframe, I got Index Dataframe instead of MultiIndex Dataframe and It has no index name and column name in there.\r\n\r\nIs this the correct behavior or this is a bug. If this is the correct one, do you have any suggestions for me to handle this?\r\n\r\nThank you in advance.\r\n\r\n## Code Sample\r\n\r\n```python\r\npd.__version__\r\n# non-empty data\r\ndata = pd.DataFrame([(1,1,1,1,1,1),(2,2,2,2,2,2)],columns=('Project', 'Task', 'Increasing Length', 'Start Period', 'Period', 'Value'))\r\ndata.set_index(['Project', 'Task', 'Increasing Length', 'Start Period', 'Period'], inplace=True)\r\nsum_data = data.sum(level=['Project', 'Task'])\r\nprint(sum_data)\r\n\r\n# empty data\r\nempty_data = pd.DataFrame([],columns=('Project', 'Task', 'Increasing Length', 'Start Period', 'Period', 'Value'))\r\nempty_data.set_index(['Project', 'Task', 'Increasing Length', 'Start Period', 'Period'], inplace=True)\r\n# sum of empty data\r\nsum_empty_data = empty_data.sum(level=['Project', 'Task'])\r\nprint(sum_empty_data)\r\n\r\n# my expectation\r\nexpected_sum_empty_data = pd.DataFrame([],columns=('Project', 'Task', 'Value'))\r\nexpected_sum_empty_data.set_index(['Project', 'Task'], inplace=True)\r\nprint(expected_sum_empty_data)\r\n```\r\n## Expected Output\r\n![image](https://user-images.githubusercontent.com/5256282/112418964-1775c080-8d5d-11eb-9caa-4e2852b6f39c.png)\r\n\r\n## Installed Version\r\npython : 3.8.8  \r\npandas : 1.2.3\r\nnumpy : 1.20.1\r\nOS: Ubuntu 20.04.1 LTS (docker)\r\n",
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40625',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40625/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40625/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40625/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/40625',
  'id': 840532139,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NjAwNDA1MzQz',
  'number': 40625,
  'title': 'REF: SingleBlockManager dont subclass BlockManager',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2021-03-25T03:54:12Z',
  'updated_at': '2021-03-25T03:54:12Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/40625',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/40625',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/40625.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/40625.patch'},
  'body': "Instead, most of BlockManager becomes _BlockManager which is subclassed by SingleBlockManager and BlockManager, the latter holding only the 2d-specific BM methods.\r\n\r\nMotivation: putting BlockManager constructor in cython gives a much bigger gain if we can define `__cinit__`, and we can't do that with the two subclasses having mismatched `__init__` signatures.",
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40624',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40624/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40624/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40624/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/40624',
  'id': 840479252,
  'node_id': 'MDU6SXNzdWU4NDA0NzkyNTI=',
  'number': 40624,
  'title': "BUG: Arithmetic operations on 0 length ExtensionArrays aren't tested",
  'user': {'login': 'andrewgsavage',
   'id': 13157776,
   'node_id': 'MDQ6VXNlcjEzMTU3Nzc2',
   'avatar_url': 'https://avatars.githubusercontent.com/u/13157776?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/andrewgsavage',
   'html_url': 'https://github.com/andrewgsavage',
   'followers_url': 'https://api.github.com/users/andrewgsavage/followers',
   'following_url': 'https://api.github.com/users/andrewgsavage/following{/other_user}',
   'gists_url': 'https://api.github.com/users/andrewgsavage/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/andrewgsavage/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/andrewgsavage/subscriptions',
   'organizations_url': 'https://api.github.com/users/andrewgsavage/orgs',
   'repos_url': 'https://api.github.com/users/andrewgsavage/repos',
   'events_url': 'https://api.github.com/users/andrewgsavage/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/andrewgsavage/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2021-03-25T01:41:01Z',
  'updated_at': '2021-03-25T01:41:01Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': "pint-pandas includes the arithmetic tests, but had an issue opened for performing addition on a 0 length PintArray. I don't think this is tested in the EA tests.\r\n\r\n```\r\nimport pint_pandas \r\nimport numpy as np\r\nimport pint\r\nimport pandas as pd\r\n\r\nPA_= pint_pandas.PintArray\r\nPT_ = pint_pandas.PintType\r\nureg=pint.get_application_registry()\r\n\r\ndata = PA_.from_1darray_quantity(\r\n        np.arange(start=1.0, stop=101.0) * ureg.nm\r\n    )\r\ns = pd.Series(data)\r\ns.loc[[]] + (1 * ureg.meter) # Untested\r\n```",
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40623',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40623/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40623/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40623/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/40623',
  'id': 840446554,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NjAwMzMyNzcz',
  'number': 40623,
  'title': 'TYP: intp in libalgos',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2021-03-25T01:03:13Z',
  'updated_at': '2021-03-25T01:36:46Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/40623',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/40623',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/40623.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/40623.patch'},
  'body': '- [ ] closes #xxxx\r\n- [ ] tests added / passed\r\n- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\r\n- [ ] whatsnew entry\r\n',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40622',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40622/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40622/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/40622/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/40622',
  'id': 840437297,
  'node_id': 'MDU6SXNzdWU4NDA0MzcyOTc=',
  'number': 40622,
  'title': 'ENH: How about "cannot reindex from an index with duplicate values"?',
  'user': {'login': 'jabowery',
   'id': 57646,
   'node_id': 'MDQ6VXNlcjU3NjQ2',
   'avatar_url': 'https://avatars.githubusercontent.com/u/57646?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jabowery',
   'html_url': 'https://github.com/jabowery',
   'followers_url': 'https://api.github.com/users/jabowery/followers',
   'following_url': 'https://api.github.com/users/jabowery/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jabowery/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jabowery/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jabowery/subscriptions',
   'organizations_url': 'https://api.github.com/users/jabowery/orgs',
   'repos_url': 'https://api.github.com/users/jabowery/repos',
   'events_url': 'https://api.github.com/users/jabowery/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jabowery/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 134699,
    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs',
    'name': 'Docs',
    'color': '3465A4',
    'default': False,
    'description': None},
   {'id': 76812,
    'node_id': 'MDU6TGFiZWw3NjgxMg==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement',
    'name': 'Enhancement',
    'color': '4E9A06',
    'default': False,
    'description': None},
   {'id': 2822098,
    'node_id': 'MDU6TGFiZWwyODIyMDk4',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing',
    'name': 'Indexing',
    'color': '0b02e1',
    'default': False,
    'description': 'Related to indexing on series/frames, not to indexes themselves'},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2021-03-25T00:55:53Z',
  'updated_at': '2021-03-25T02:17:42Z',

In [16]:
data[2]['user']

{'login': 'llthelinkll',
 'id': 5256282,
 'node_id': 'MDQ6VXNlcjUyNTYyODI=',
 'avatar_url': 'https://avatars.githubusercontent.com/u/5256282?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/llthelinkll',
 'html_url': 'https://github.com/llthelinkll',
 'followers_url': 'https://api.github.com/users/llthelinkll/followers',
 'following_url': 'https://api.github.com/users/llthelinkll/following{/other_user}',
 'gists_url': 'https://api.github.com/users/llthelinkll/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/llthelinkll/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/llthelinkll/subscriptions',
 'organizations_url': 'https://api.github.com/users/llthelinkll/orgs',
 'repos_url': 'https://api.github.com/users/llthelinkll/repos',
 'events_url': 'https://api.github.com/users/llthelinkll/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/llthelinkll/received_events',
 'type': 'User',
 'site_admin': False}

In [17]:
data[2] ['user'] ['id']

5256282

In [18]:
import pandas as pd

In [19]:
issues=pd.DataFrame(data)

In [20]:
issues

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,pull_request,body,performed_via_github_app
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40629,840609480,MDExOlB1bGxSZXF1ZXN0NjAwNDcxMTM1,40629,Detect Parsing errors in read_csv first row wi...,...,None,0,2021-03-25T06:32:30Z,2021-03-25T07:10:04Z,None,NONE,None,{'url': 'https://api.github.com/repos/pandas-d...,\r\n- [X] closes #40333\r\n- [ ] tests added /...,None
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40628,840584176,MDExOlB1bGxSZXF1ZXN0NjAwNDQ5NjU0,40628,New boundary inputs,...,None,1,2021-03-25T05:52:36Z,2021-03-25T06:29:50Z,None,NONE,None,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #40245\r\n- [x] tests added / pas...,None
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/40626,840554057,MDU6SXNzdWU4NDA1NTQwNTc=,40626,BUG: I got empty Dataframe with index from the...,...,None,0,2021-03-25T04:49:03Z,2021-03-25T06:26:43Z,None,NONE,None,NaN,I'm not sure that the current behavior is righ...,None
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40625,840532139,MDExOlB1bGxSZXF1ZXN0NjAwNDA1MzQz,40625,REF: SingleBlockManager dont subclass BlockMan...,...,None,0,2021-03-25T03:54:12Z,2021-03-25T03:54:12Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,"Instead, most of BlockManager becomes _BlockMa...",None
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/40624,840479252,MDU6SXNzdWU4NDA0NzkyNTI=,40624,BUG: Arithmetic operations on 0 length Extensi...,...,None,0,2021-03-25T01:41:01Z,2021-03-25T01:41:01Z,None,NONE,None,NaN,"pint-pandas includes the arithmetic tests, but...",None
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40623,840446554,MDExOlB1bGxSZXF1ZXN0NjAwMzMyNzcz,40623,TYP: intp in libalgos,...,None,0,2021-03-25T01:03:13Z,2021-03-25T01:36:46Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx\r\n- [ ] tests added / pass...,None
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/40622,840437297,MDU6SXNzdWU4NDA0MzcyOTc=,40622,"ENH: How about ""cannot reindex from an index w...",...,None,1,2021-03-25T00:55:53Z,2021-03-25T02:17:42Z,None,NONE,None,NaN,#### Is your feature request related to a prob...,None
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40621,840318176,MDExOlB1bGxSZXF1ZXN0NjAwMjExNTEw,40621,BUG: groupby any/all raising on extension types,...,None,1,2021-03-24T23:24:08Z,2021-03-25T02:02:37Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #40585\r\n- [x] tests added / pas...,None
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40620,840164941,MDExOlB1bGxSZXF1ZXN0NjAwMDcwMDU4,40620,PERF: cache_readonly for Block properties,...,None,1,2021-03-24T21:07:12Z,2021-03-24T21:54:51Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,We'll be able to cache more aggressively follo...,None
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40616,840098241,MDExOlB1bGxSZXF1ZXN0NjAwMDEzNjA2,40616,DOC: _array_strptime_with_fallback method def,...,None,1,2021-03-24T19:31:56Z,2021-03-24T19:32:24Z,None,NONE,None,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx\r\n- [ ] tests added / pass...,None
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40614,839995995,MDExOlB1bGxSZXF1ZXN0NTk5OTIzNTky,40614,"REF: remove DatetimeBlock, TimeDeltaBlock",...,None,0,2021-03-24T17:49:41Z,2021-03-24T17:49:41Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,sits on top of #40456,None
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/40613,839890067,MDU6SXNzdWU4Mzk4OTAwNjc=,40613,Add capability to upsample with .resample().ff...,...,None,0,2021-03-24T16:13:21Z,2021-03-24T16:13:21Z,None,NONE,None,NaN,It would be good to have the capability to ups...,None
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40612,839859959,MDExOlB1bGxSZXF1ZXN0NTk5ODA1Nzg2,40612,TYP: get_indexer,...,None,0,2021-03-24T15:42:31Z,2021-03-24T21:25:39Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,@simonjayhawkins im at a loss on why im gettin...,None
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/40611,839737047,MDU6SXNzdWU4Mzk3MzcwNDc=,40611,Can't install Pandas on Mac M1,...,None,5,2021-03-24T13:42:17Z,2021-03-25T08:05:46Z,None,NONE,None,NaN,Environment\r\nMac M1\r\nPython 3.8.2 created ...,None
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/40608,839485332,MDU6SXNzdWU4Mzk0ODUzMzI=,40608,BUG: join/merge of DataFrame does not keep ord...,...,None,0,2021-03-24T08:38:30Z,2021-03-25T02:19:29Z,None,CONTRIBUTOR,None,NaN,- [x] I have checked that this issue has not a...,None
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/40607,839446905,MDU6SXNzdWU4Mzk0NDY5MDU=,40607,QST:,...,None,1,2021-03-24T07:44:24Z,2021-03-24T09:17:30Z,None,NONE,None,NaN,why my plotnine cant be applied? this is that ...,None
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/40606,839437943,MDU6SXNzdWU4Mzk0Mzc5NDM=,40606,DEPR: deprecate setting Categorical._codes,...,{'url': 'https://api.github.com/repos/pandas-d...,0,2021-03-24T07:30:45Z,2021-03-24T07:30:45Z,None,MEMBER,None,NaN,Needed follow-up on https://github.com/pandas-...,None
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/40605,839339620,MDU6SXNzdWU4MzkzMzk2MjA=,40605,BUG: color list passed in as list/array/series...,...,None,0,2021-03-24T04:37:24Z,2021-03-24T04:37:24Z,None,NONE,None,NaN,So I found this issue was fixed in 2017 and 20...,None
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/40603,839269593,MDU6SXNzdWU4MzkyNjk1OTM=,40603,March 2021 Docs Meeting,...,None,2,2021-03-24T02:00:45Z,2021-03-24T21:44:13Z,None,MEMBER,None,NaN,"- [Thursday, March 25th 9-10am US Eastern Time...",None
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40602,839203759,MDExOlB1bGxSZXF1ZXN0NTk5MjU2MDI5,40602,ENH: Categorical.empty,...,None,7,2021-03-23T23:28:00Z,2021-03-24T15:17:51Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx\r\n- [ ] tests added / pass...,None
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40600,839181294,MDExOlB1bGxSZXF1ZXN0NTk5MjM3MDIz,40600,DOC: _guess_time_format_for_array method desc,...,None,1,2021-03-23T22:43:29Z,2021-03-24T15:16:02Z,None,NONE,None,{'url': 'https://api.github.com/repos/pandas-d...,Method description added for the method\r\n\r\...,None
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40597,839137947,MDExOlB1bGxSZXF1ZXN0NTk5MjAwMjM1,40597,DOC: update,...,None,1,2021-03-23T21:26:46Z,2021-03-23T21:34:32Z,None,NONE,None,{'url': 'https://api.github.com/repos/pandas-d...,added extended param definition\r\n\r\n- [ ] c...,None
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40596,839111448,MDExOlB1bGxSZXF1ZXN0NTk5MTc3MzQ1,40596,ENH: add `decimal` and `thousands` args to `St...,...,{'url': 'https://api.github.com/repos/pandas-d...,0,2021-03-23T20:51:09Z,2021-03-24T06:11:31Z,None,CONTRIBUTOR,None,{'url': 'https://api.github.com/repos/pandas-d...,A PR for Europeans:\r\n\r\n![Screen Shot 2021-...,None
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40594,839080244,MDExOlB1bGxSZXF1ZXN0NTk5MTUwMzQx,40594,TYP: testing.pyi,...,None,0,2021-03-23T20:09:19Z,2021-03-24T13:54:50Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx\r\n- [ ] tests added / pass...,None
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40593,839074875,MDExOlB1bGxSZXF1ZXN0NTk5MTQ1NzQy,40593,TST Add test for loc on sparse dataframes,...,None,1,2021-03-23T20:01:24Z,2021-03-24T09:55:49Z,None,NONE,None,{'url': 'https://api.github.com/repos/pandas-d...,Adds a test for loc on sparse dataframes.\r\n\...,None
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/40591,838843661,MDU6SXNzdWU4Mzg4NDM2NjE=,40591,QST: Related to working of `as_index` in panda...,...,None,2,2021-03-23T15:24:41Z,2021-03-25T02:45:22Z,None,NONE,None,NaN,- [X] I have searched the [[pandas] tag](https...,None
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/40590,838838592,MDExOlB1bGxSZXF1ZXN0NTk4OTUwNDY4,40590,Backport PR #40525 on branch 1.2.x (BUG: to_js...,...,{'url': 'https://api.github.com/repos/pandas-d...,0,2021-03-23T15:19:33Z,2021-03-23T15:42:45Z,None,NONE,None,{'url': 'https://api.github.com/repos/pandas-d...,Backport PR #40525: BUG: to_json failing on PyPy,None
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/40589,838837024,MDU6SXNzdWU4Mzg4MzcwMjQ=,40589,BUG: converters of dtype is ignored in read_cs...,...,None,0,2021-03-23T15:18:02Z,2021-03-23T15:18:02Z,None,NONE,None,NaN,- [x ] I have checked that this issue has not ...,None
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/40588,838814171,MDU6SXNzdWU4Mzg4MTQxNzE=,40588,Index=False is not working in to_parquet command,...,None,5,2021-03-23T14:54:53Z,2021-03-24T17:01:09Z,None,NONE,None,NaN,import pandas as pd\r\ndf = pd.DataFrame(data=...,None
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/40587,838813228,MDU6SXNzdWU4Mzg4MTMyMjg=,40587,"BUG: Occasional ""tokenizing data error"" when r...",...,None,2,2021-03-23T14:54:02Z,2021-03-25T01:15:41Z,None,NONE,None,NaN,I sometimes receive a `Error tokenizing data. ...,None

# Pandas data time Manipulation

In [21]:
import numpy as np
import pandas as pd

In [23]:
dates=pd.date_range('1/1/2000',periods=7)
dates

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07'],
              dtype='datetime64[ns]', freq='D')

In [24]:
pd.date_range('1/1/2000',periods=10,freq='m')

DatetimeIndex(['2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30',
               '2000-05-31', '2000-06-30', '2000-07-31', '2000-08-31',
               '2000-09-30', '2000-10-31'],
              dtype='datetime64[ns]', freq='M')

In [25]:
pd.date_range('1/1/2000',periods=12,freq='y')

DatetimeIndex(['2000-12-31', '2001-12-31', '2002-12-31', '2003-12-31',
               '2004-12-31', '2005-12-31', '2006-12-31', '2007-12-31',
               '2008-12-31', '2009-12-31', '2010-12-31', '2011-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')

In [30]:
dates=pd.date_range('1/1/2000',periods=7)
ts=pd.Series(np.arange(7),index=dates)
ts

2000-01-01    0
2000-01-02    1
2000-01-03    2
2000-01-04    3
2000-01-05    4
2000-01-06    5
2000-01-07    6
Freq: D, dtype: int32

In [32]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [33]:
ts.to_csv(r"C:\Users\HP\Desktop\python project\datefile.csv")

# Data cleaning

Handling missing data

In [34]:
import numpy as np
import pandas as pd
val1=np.array([1,np.nan,7,1,8])
val1

array([ 1., nan,  7.,  1.,  8.])

In [35]:
6+np.nan

nan

In [36]:
7*np.nan

nan

In [37]:
np.nansum(val1)

17.0

# Nan and None in pandas

In [39]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

Create DataFrame with missing value

In [48]:
raw_data={'first_name':['vikas',np.nan,'tina','hena','avi'],
         'last_name':['rajput',np.nan,'pal','raj','nash'],
         'age':['22',np.nan,23,24,25],
         'sex':['M',np.nan,'F','F','M'],
         'pretestscore':[4,np.nan,np.nan,2,3],
         'posttestscore':[25,np.nan,np.nan,62,70]}
df=pd.DataFrame(raw_data,columns=['first_name','last_name','age','sex','pretestscore','posttestscore'])
df

  first_name last_name  age  sex  pretestscore  posttestscore
0      vikas    rajput   22    M           4.0           25.0
1        NaN       NaN  NaN  NaN           NaN            NaN
2       tina       pal   23    F           NaN            NaN
3       hena       raj   24    F           2.0           62.0
4        avi      nash   25    M           3.0           70.0

# Drop missing observations

In [49]:
df_no_missing=df.dropna()
df_no_missing

  first_name last_name age sex  pretestscore  posttestscore
0      vikas    rajput  22   M           4.0           25.0
3       hena       raj  24   F           2.0           62.0
4        avi      nash  25   M           3.0           70.0

# Drop rows where all cells in that raw in NA

In [51]:
df_cleaned=df.dropna(how='all')

In [52]:
df_cleaned

  first_name last_name age sex  pretestscore  posttestscore
0      vikas    rajput  22   M           4.0           25.0
2       tina       pal  23   F           NaN            NaN
3       hena       raj  24   F           2.0           62.0
4        avi      nash  25   M           3.0           70.0

# Create a new column full of missing values

In [53]:
df['location']=np.nan

In [54]:
df

  first_name last_name  age  sex  pretestscore  posttestscore  location
0      vikas    rajput   22    M           4.0           25.0       NaN
1        NaN       NaN  NaN  NaN           NaN            NaN       NaN
2       tina       pal   23    F           NaN            NaN       NaN
3       hena       raj   24    F           2.0           62.0       NaN
4        avi      nash   25    M           3.0           70.0       NaN

# Drop column if they only contain missing values

In [59]:
df.dropna(axis=1,how='all')

  first_name last_name  age  sex  pretestscore  posttestscore
0      vikas    rajput   22    M           4.0           25.0
1        NaN       NaN  NaN  NaN           NaN            NaN
2       tina       pal   23    F           NaN            NaN
3       hena       raj   24    F           2.0           62.0
4        avi      nash   25    M           3.0           70.0

In [60]:
df.fillna(0)

  first_name last_name age sex  pretestscore  posttestscore  location
0      vikas    rajput  22   M           4.0           25.0       0.0
1          0         0   0   0           0.0            0.0       0.0
2       tina       pal  23   F           0.0            0.0       0.0
3       hena       raj  24   F           2.0           62.0       0.0
4        avi      nash  25   M           3.0           70.0       0.0

# File in missing in pretestscore with the mean value of pretestscore

In [61]:
df['pretestscore'].fillna(df['pretestscore'].mean(),inplace=True)

In [62]:
df

  first_name last_name  age  sex  pretestscore  posttestscore  location
0      vikas    rajput   22    M           4.0           25.0       NaN
1        NaN       NaN  NaN  NaN           3.0            NaN       NaN
2       tina       pal   23    F           3.0            NaN       NaN
3       hena       raj   24    F           2.0           62.0       NaN
4        avi      nash   25    M           3.0           70.0       NaN

# Fill in missing in posttestscore with each sex's mean value of posttestscore

In [63]:
df["posttestscore"].fillna(df.groupby("sex")["posttestscore"].transform("mean"),inplace=True)

In [64]:
df

  first_name last_name  age  sex  pretestscore  posttestscore  location
0      vikas    rajput   22    M           4.0           25.0       NaN
1        NaN       NaN  NaN  NaN           3.0            NaN       NaN
2       tina       pal   23    F           3.0           62.0       NaN
3       hena       raj   24    F           2.0           62.0       NaN
4        avi      nash   25    M           3.0           70.0       NaN

# Select some raws but ignore the missing data points

In [67]:
df[df['age'].notnull() & df["sex"].notnull()]

  first_name last_name age sex  pretestscore  posttestscore  location
0      vikas    rajput  22   M           4.0           25.0       NaN
2       tina       pal  23   F           3.0           62.0       NaN
3       hena       raj  24   F           2.0           62.0       NaN
4        avi      nash  25   M           3.0           70.0       NaN

# Back-fill

In [68]:
df.fillna(method='bfill')

  first_name last_name age sex  pretestscore  posttestscore  location
0      vikas    rajput  22   M           4.0           25.0       NaN
1       tina       pal  23   F           3.0           62.0       NaN
2       tina       pal  23   F           3.0           62.0       NaN
3       hena       raj  24   F           2.0           62.0       NaN
4        avi      nash  25   M           3.0           70.0       NaN

# Forward fill

In [69]:
df.fillna(method='ffill',axis=1)

  first_name last_name  age  sex pretestscore posttestscore location
0      vikas    rajput   22    M            4            25       25
1        NaN       NaN  NaN  NaN            3             3        3
2       tina       pal   23    F            3            62       62
3       hena       raj   24    F            2            62       62
4        avi      nash   25    M            3            70       70

# Hierarchical Indexing

# Create DataFrame

In [108]:
row_data={'regiment':['nighthawks','nighthawks','nighthawks','nighthawks','dragoon','dragoon','dragoon','dragoon','scouts','scouts','scouts','scouts'],
         'company':['1st','1st','2nd','2nd','1st','1st','2nd','2nd','1st','1st','2nd','2nd'],
         'name':['miller','jackson','ali','milner','cooze','jackson','ryaner','soni','slaon','piger','riani','ali'],
         'preTestscore':[4,24,31,2,3,4,24,31,2,3,2,3],
         'postTestscore':[25,94,57,62,70,25,94,57,62,70,62,70]}

df=pd.DataFrame(row_data,columns=['regiment','company','name','preTestscore','postTestscore'])
df

      regiment company     name  preTestscore  postTestscore
0   nighthawks     1st   miller             4             25
1   nighthawks     1st  jackson            24             94
2   nighthawks     2nd      ali            31             57
3   nighthawks     2nd   milner             2             62
4      dragoon     1st    cooze             3             70
5      dragoon     1st  jackson             4             25
6      dragoon     2nd   ryaner            24             94
7      dragoon     2nd     soni            31             57
8       scouts     1st    slaon             2             62
9       scouts     1st    piger             3             70
10      scouts     2nd    riani             2             62
11      scouts     2nd      ali             3             70

# Set the hierarchical index but leave the columns inplace

In [109]:
df.set_index(['regiment','company'],drop=False)

                      regiment company     name  preTestscore  postTestscore
regiment   company
nighthawks 1st      nighthawks     1st   miller             4             25
           1st      nighthawks     1st  jackson            24             94
           2nd      nighthawks     2nd      ali            31             57
           2nd      nighthawks     2nd   milner             2             62
dragoon    1st         dragoon     1st    cooze             3             70
           1st         dragoon     1st  jackson             4             25
           2nd         dragoon     2nd   ryaner            24             94
           2nd         dragoon     2nd     soni            31             57
scouts     1st          scouts     1st    slaon             2             62
           1st          scouts     1st    piger             3             70
           2nd          scouts     2nd    riani             2             62
           2nd          scouts     2nd      ali             3             70

# Set the hierrarchical index to be by regiment and then by company

In [110]:
df.set_index(['regiment','company'],inplace=True)

In [111]:
df

                       name  preTestscore  postTestscore
regiment   company
nighthawks 1st       miller             4             25
           1st      jackson            24             94
           2nd          ali            31             57
           2nd       milner             2             62
dragoon    1st        cooze             3             70
           1st      jackson             4             25
           2nd       ryaner            24             94
           2nd         soni            31             57
scouts     1st        slaon             2             62
           1st        piger             3             70
           2nd        riani             2             62
           2nd          ali             3             70

# Swap the level in the index

In [112]:
df.swaplevel('regiment','company')

                       name  preTestscore  postTestscore
company regiment
1st     nighthawks   miller             4             25
        nighthawks  jackson            24             94
2nd     nighthawks      ali            31             57
        nighthawks   milner             2             62
1st     dragoon       cooze             3             70
        dragoon     jackson             4             25
2nd     dragoon      ryaner            24             94
        dragoon        soni            31             57
1st     scouts        slaon             2             62
        scouts        piger             3             70
2nd     scouts        riani             2             62
        scouts          ali             3             70

# Summarize the result by regiment

In [114]:
df.sum(level="regiment")

            preTestscore  postTestscore
regiment
nighthawks            61            238
dragoon               62            246
scouts                10            264

# Pandas Data manipulation

In [29]:
import pandas as pd
import numpy as np

In [4]:
titanic_train=pd.read_csv(r'C:\Users\HP\Desktop\python file\titanic_train.csv')

In [5]:
titanic_train.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
new_survived=pd.Categorical(titanic_train['Survived'])

In [7]:
new_survived

[0, 1, 1, 1, 0, ..., 0, 1, 0, 1, 0]
Length: 891
Categories (2, int64): [0, 1]

In [9]:
new_survived=new_survived.rename_categories(['died','survived'])
new_survived

['died', 'survived', 'survived', 'survived', 'died', ..., 'died', 'survived', 'died', 'survived', 'died']
Length: 891
Categories (2, object): ['died', 'survived']

In [10]:
new_survived.describe()

            counts     freqs
categories
died           549  0.616162
survived       342  0.383838

In [24]:
new_Pclass=pd.Categorical(titanic_train['Pclass'],ordered=True)
new_Pclass=new_Pclass.rename_categories(['class1','class2','calss3'])
new_Pclass.describe()

            counts     freqs
categories
class1         216  0.242424
class2         184  0.206510
calss3         491  0.551066

In [25]:
titanic_train['Pclass']=new_Pclass
titanic_train.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,calss3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,class1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,calss3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,class1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,calss3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
titanic_train['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [31]:
char_Cabin=titanic_train['Cabin'].astype(str)
new_Cabin=np.array([Cabin[0]for Cabin in char_Cabin])
new_cabin=pd.Categorical(new_Cabin)
new_cabin.describe()

            counts     freqs
categories
A               15  0.016835
B               47  0.052750
C               59  0.066218
D               33  0.037037
E               32  0.035915
F               13  0.014590
G                4  0.004489
T                1  0.001122
n              687  0.771044

In [32]:
titanic_train['Cabin']=new_Cabin
titanic_train.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,calss3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,n,S
1,1,2,1,class1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,2,3,1,calss3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,n,S
3,3,4,1,class1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,4,5,0,calss3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,n,S

In [36]:
dummy_vector=pd.Series([1,None,3,None,7,8])
dummy_vector.isnull()

0    False
1     True
2    False
3     True
4    False
5    False
dtype: bool

In [38]:
missing=np.where(titanic_train['Age'].isnull()==True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dtype=int64),)

In [39]:
len(missing[0])

177

In [40]:
index=np.where(titanic_train['Fare']==max(titanic_train['Fare']))
index

(array([258, 679, 737], dtype=int64),)

In [42]:
titanic_train.loc[index]

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,258,259,1,class1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,n,C
679,679,680,1,class1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B,C
737,737,738,1,class1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B,C

In [44]:
titanic_train['family']=titanic_train['SibSp']+titanic_train['Parch']
most_family=np.where(titanic_train['family']==max(titanic_train['family']))

In [56]:

titanic_train.index[most_family]

Int64Index([159, 180, 201, 324, 792, 846, 863], dtype='int64')